### ISSUE TITLE
homeassistant configuration

### ISSUE THREAD

**Issue by ollieatkinson** [ollieatkinson/home#2]
Check and add the following (and maybe customize):

```yaml
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London
```
